server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogsy?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  secret: your-jwt-secret-key
  expiration: 3600000