server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/blogsy?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  secret: my-super-secret-jwt-key-which-should-be-long
  expiration: 36000

openai:
  api:
    key: ${OPENAI_API_KEY}
    embedding:
      url: https://api.openai.com/v1/embeddings
  model: text-embedding-3-small
